//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Telnetmfc.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TELNETTYPE                  129
#define IDD_CONNECT                     130
#define IDC_EDIT_REMSYS                 1000
#define IDC_EDIT_PORT                   1001
#define ID_CONNECT_REMOTESYSTEM         32771
#define ID_CONNECT_DISCONNECT           32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
